micronaut:
  application:
    name: arkondataTest

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/arkon_data_pipeline
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

---
jpa:
  default:
    packages-to-scan:
      - 'com.raulagl.arkondatatest'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false

flyway:
  datasources:
    default:
      locations: classpath:db/migration

---