micronaut:
  application:
    name: arkondataTest

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5430/arkon_data_pipeline`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:123456}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}


jpa:
  default:
    packages-to-scan:
      - 'com.raulagl.arkondatatest'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false

flyway:
  datasources:
    default:
      enabled: true
